# Generated by Django 4.2 on 2023-08-29 17:31

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=django_fsm.FSMField(choices=[('moderation', 'Moderation'), ('published', 'Published'), ('deleted', 'Deleted'), ('rejected', 'Rejected')], default='moderation', max_length=50, protected=True),
        ),
    ]
