# Generated by Django 4.2 on 2023-08-29 18:22

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=django_fsm.FSMField(choices=[('mod', 'Moderation'), ('pub', 'Published'), ('del', 'Deleted'), ('rej', 'Rejected')], default='mod', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
