# Generated by Django 4.2 on 2023-10-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0005_alter_comment_post_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-total_likes'], name='models_app__total_l_82a699_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-total_comments'], name='models_app__total_c_c4b30a_idx'),
        ),
    ]
