# Generated by Django 4.2 on 2023-10-03 13:03

import django.core.validators
from django.db import migrations, models
import models_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_post_total_comments_post_total_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='image/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('gif', 'jpg', 'jpeg', 'png')), models_app.validators.validate_image_file_size, models_app.validators.validate_image_dimensions]),
        ),
    ]
